name: Request 10GB-CI

on:
  push:
  pull_request:

jobs:
  request-10GB-CI:
    runs-on: ubuntu-latest
    steps:
      - name: Request 10GB-CI
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"
          curl -X POST https://api.github.com/repos/webyrd/mediKanren-ops/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.GH_ACCESS_TOKEN }} \
          --data '{"event_type": "ping", "client_payload": {
              "repository": "'"$GITHUB_REPOSITORY"'",
              "github_sha1": "'$GITHUB_SHA1'",
              "github_ref": "'$GITHUB_REF'",
              "github_head_ref": "'$GITHUB_HEAD_REF'",
              "github_base_ref": "'$GITHUB_BASE_REF'"
              }}'
